// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: proto/talondb.proto

package talondbpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TalonDBService_Put_FullMethodName                = "/opentalon.talondb.v1.TalonDBService/Put"
	TalonDBService_Get_FullMethodName                = "/opentalon.talondb.v1.TalonDBService/Get"
	TalonDBService_Delete_FullMethodName             = "/opentalon.talondb.v1.TalonDBService/Delete"
	TalonDBService_BatchPut_FullMethodName           = "/opentalon.talondb.v1.TalonDBService/BatchPut"
	TalonDBService_Lookup_FullMethodName             = "/opentalon.talondb.v1.TalonDBService/Lookup"
	TalonDBService_LookupPrefix_FullMethodName       = "/opentalon.talondb.v1.TalonDBService/LookupPrefix"
	TalonDBService_LookupNumericRange_FullMethodName = "/opentalon.talondb.v1.TalonDBService/LookupNumericRange"
	TalonDBService_WindowQuery_FullMethodName        = "/opentalon.talondb.v1.TalonDBService/WindowQuery"
	TalonDBService_GroupCount_FullMethodName         = "/opentalon.talondb.v1.TalonDBService/GroupCount"
	TalonDBService_Stats_FullMethodName              = "/opentalon.talondb.v1.TalonDBService/Stats"
	TalonDBService_LastSeen_FullMethodName           = "/opentalon.talondb.v1.TalonDBService/LastSeen"
	TalonDBService_LastWritten_FullMethodName        = "/opentalon.talondb.v1.TalonDBService/LastWritten"
	TalonDBService_Ancestors_FullMethodName          = "/opentalon.talondb.v1.TalonDBService/Ancestors"
	TalonDBService_Descendants_FullMethodName        = "/opentalon.talondb.v1.TalonDBService/Descendants"
	TalonDBService_Query_FullMethodName              = "/opentalon.talondb.v1.TalonDBService/Query"
	TalonDBService_QueryAsOf_FullMethodName          = "/opentalon.talondb.v1.TalonDBService/QueryAsOf"
	TalonDBService_SequenceJoin_FullMethodName       = "/opentalon.talondb.v1.TalonDBService/SequenceJoin"
	TalonDBService_ClusterQuery_FullMethodName       = "/opentalon.talondb.v1.TalonDBService/ClusterQuery"
	TalonDBService_VectorInsert_FullMethodName       = "/opentalon.talondb.v1.TalonDBService/VectorInsert"
	TalonDBService_VectorSearch_FullMethodName       = "/opentalon.talondb.v1.TalonDBService/VectorSearch"
	TalonDBService_VectorDelete_FullMethodName       = "/opentalon.talondb.v1.TalonDBService/VectorDelete"
	TalonDBService_VectorDropScope_FullMethodName    = "/opentalon.talondb.v1.TalonDBService/VectorDropScope"
	TalonDBService_VectorListScopes_FullMethodName   = "/opentalon.talondb.v1.TalonDBService/VectorListScopes"
	TalonDBService_Subscribe_FullMethodName          = "/opentalon.talondb.v1.TalonDBService/Subscribe"
	TalonDBService_Health_FullMethodName             = "/opentalon.talondb.v1.TalonDBService/Health"
)

// TalonDBServiceClient is the client API for TalonDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TalonDBService is the wire surface exposed by `talondb-server`. The
// gRPC service maps 1:1 to the talondb.IndexedStore Go interface.
//
// Two transports speak this schema:
//   - gRPC, the primary protocol (Unix socket default, TCP optional).
//   - HTTP/JSON, generated by grpc-gateway from this file, useful for
//     curl-based debugging and non-Go clients. The HTTP paths follow
//     the Postgres-flavoured convention of operation-as-path, request
//     body as JSON.
type TalonDBServiceClient interface {
	// DocumentStore surface (entityID, docID) → bytes
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BatchPut(ctx context.Context, in *BatchPutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// IndexedStore lookup surface
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*DocIDList, error)
	LookupPrefix(ctx context.Context, in *LookupPrefixRequest, opts ...grpc.CallOption) (*DocIDList, error)
	LookupNumericRange(ctx context.Context, in *NumericRangeRequest, opts ...grpc.CallOption) (*DocIDList, error)
	WindowQuery(ctx context.Context, in *WindowRequest, opts ...grpc.CallOption) (*WindowResponse, error)
	GroupCount(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	LastSeen(ctx context.Context, in *LastSeenRequest, opts ...grpc.CallOption) (*LastSeenResponse, error)
	// LastWritten returns a document's updated_at time (doc-level
	// granularity). Backs the FactStore Freshness capability used for fact
	// staleness / the enrich block.
	LastWritten(ctx context.Context, in *LastWrittenRequest, opts ...grpc.CallOption) (*LastWrittenResponse, error)
	Ancestors(ctx context.Context, in *AncestorsRequest, opts ...grpc.CallOption) (*StringList, error)
	Descendants(ctx context.Context, in *DescendantsRequest, opts ...grpc.CallOption) (*DocIDList, error)
	// Query is the server-side composer for structured queries: anchor
	// narrowing via the inverted index + per-doc clause evaluation. Lets
	// non-Go clients run a multi-clause query in one round-trip instead
	// of replicating the talon-language adapter's composition logic.
	// Supported clauses: Pattern, Predicate, Or, Not, FullText.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// QueryAsOf runs the same structured composer as Query but against a
	// reconstruction of the store as it existed at at_unix_nanos. Each
	// document is rebuilt from its version history (latest version whose
	// write time is <= the timestamp; documents created later, or deleted
	// by then, are absent). Backs the FactStore TimeTraveler capability
	// that powers `was <condition> N <unit> ago` detect conditions.
	QueryAsOf(ctx context.Context, in *QueryAsOfRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// SequenceJoin scans temporal indexes for one or more items and
	// returns the items whose event log contains the requested step
	// sequence in order, with total span at most window_nanos. Empty
	// item_ids means scan every item under entity_id.
	SequenceJoin(ctx context.Context, in *SequenceJoinRequest, opts ...grpc.CallOption) (*SequenceJoinResponse, error)
	// ClusterQuery walks a (entity, itemID)'s temporal index and returns
	// non-overlapping clusters of events whose total span is at most
	// window_nanos and whose size is at least min_size. Replaces the
	// client-side "fetch all events + count" pattern for "N+ records
	// within W" detect blocks.
	ClusterQuery(ctx context.Context, in *ClusterQueryRequest, opts ...grpc.CallOption) (*ClusterQueryResponse, error)
	// Vector index — per-scope HNSW with dimension locked on first
	// insert. talon-db hosts one logical index per (entity, scope), so a
	// single tenant can hold multiple embedding models with different
	// dimensions side-by-side without cross-contamination.
	VectorInsert(ctx context.Context, in *VectorInsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error)
	VectorDelete(ctx context.Context, in *VectorDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	VectorDropScope(ctx context.Context, in *VectorDropScopeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	VectorListScopes(ctx context.Context, in *VectorListScopesRequest, opts ...grpc.CallOption) (*VectorListScopesResponse, error)
	// Subscribe streams MutationEvents for every committed Put / Delete.
	// The server-side stream stays open until the client cancels or the
	// server shuts down. SubscribeRequest filters narrow the stream
	// server-side; an empty entity_id matches every tenant, an empty
	// doc_id_prefix matches every doc.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MutationEvent], error)
	// Operational
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type talonDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTalonDBServiceClient(cc grpc.ClientConnInterface) TalonDBServiceClient {
	return &talonDBServiceClient{cc}
}

func (c *talonDBServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TalonDBService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, TalonDBService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TalonDBService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) BatchPut(ctx context.Context, in *BatchPutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TalonDBService_BatchPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*DocIDList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocIDList)
	err := c.cc.Invoke(ctx, TalonDBService_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) LookupPrefix(ctx context.Context, in *LookupPrefixRequest, opts ...grpc.CallOption) (*DocIDList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocIDList)
	err := c.cc.Invoke(ctx, TalonDBService_LookupPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) LookupNumericRange(ctx context.Context, in *NumericRangeRequest, opts ...grpc.CallOption) (*DocIDList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocIDList)
	err := c.cc.Invoke(ctx, TalonDBService_LookupNumericRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) WindowQuery(ctx context.Context, in *WindowRequest, opts ...grpc.CallOption) (*WindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WindowResponse)
	err := c.cc.Invoke(ctx, TalonDBService_WindowQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) GroupCount(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, TalonDBService_GroupCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, TalonDBService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) LastSeen(ctx context.Context, in *LastSeenRequest, opts ...grpc.CallOption) (*LastSeenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastSeenResponse)
	err := c.cc.Invoke(ctx, TalonDBService_LastSeen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) LastWritten(ctx context.Context, in *LastWrittenRequest, opts ...grpc.CallOption) (*LastWrittenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastWrittenResponse)
	err := c.cc.Invoke(ctx, TalonDBService_LastWritten_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) Ancestors(ctx context.Context, in *AncestorsRequest, opts ...grpc.CallOption) (*StringList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringList)
	err := c.cc.Invoke(ctx, TalonDBService_Ancestors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) Descendants(ctx context.Context, in *DescendantsRequest, opts ...grpc.CallOption) (*DocIDList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocIDList)
	err := c.cc.Invoke(ctx, TalonDBService_Descendants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, TalonDBService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) QueryAsOf(ctx context.Context, in *QueryAsOfRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, TalonDBService_QueryAsOf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) SequenceJoin(ctx context.Context, in *SequenceJoinRequest, opts ...grpc.CallOption) (*SequenceJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SequenceJoinResponse)
	err := c.cc.Invoke(ctx, TalonDBService_SequenceJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) ClusterQuery(ctx context.Context, in *ClusterQueryRequest, opts ...grpc.CallOption) (*ClusterQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterQueryResponse)
	err := c.cc.Invoke(ctx, TalonDBService_ClusterQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) VectorInsert(ctx context.Context, in *VectorInsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TalonDBService_VectorInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorSearchResponse)
	err := c.cc.Invoke(ctx, TalonDBService_VectorSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) VectorDelete(ctx context.Context, in *VectorDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TalonDBService_VectorDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) VectorDropScope(ctx context.Context, in *VectorDropScopeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TalonDBService_VectorDropScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) VectorListScopes(ctx context.Context, in *VectorListScopesRequest, opts ...grpc.CallOption) (*VectorListScopesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorListScopesResponse)
	err := c.cc.Invoke(ctx, TalonDBService_VectorListScopes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talonDBServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MutationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TalonDBService_ServiceDesc.Streams[0], TalonDBService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, MutationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TalonDBService_SubscribeClient = grpc.ServerStreamingClient[MutationEvent]

func (c *talonDBServiceClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TalonDBService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TalonDBServiceServer is the server API for TalonDBService service.
// All implementations must embed UnimplementedTalonDBServiceServer
// for forward compatibility.
//
// TalonDBService is the wire surface exposed by `talondb-server`. The
// gRPC service maps 1:1 to the talondb.IndexedStore Go interface.
//
// Two transports speak this schema:
//   - gRPC, the primary protocol (Unix socket default, TCP optional).
//   - HTTP/JSON, generated by grpc-gateway from this file, useful for
//     curl-based debugging and non-Go clients. The HTTP paths follow
//     the Postgres-flavoured convention of operation-as-path, request
//     body as JSON.
type TalonDBServiceServer interface {
	// DocumentStore surface (entityID, docID) → bytes
	Put(context.Context, *PutRequest) (*emptypb.Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	BatchPut(context.Context, *BatchPutRequest) (*emptypb.Empty, error)
	// IndexedStore lookup surface
	Lookup(context.Context, *LookupRequest) (*DocIDList, error)
	LookupPrefix(context.Context, *LookupPrefixRequest) (*DocIDList, error)
	LookupNumericRange(context.Context, *NumericRangeRequest) (*DocIDList, error)
	WindowQuery(context.Context, *WindowRequest) (*WindowResponse, error)
	GroupCount(context.Context, *GroupRequest) (*GroupResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	LastSeen(context.Context, *LastSeenRequest) (*LastSeenResponse, error)
	// LastWritten returns a document's updated_at time (doc-level
	// granularity). Backs the FactStore Freshness capability used for fact
	// staleness / the enrich block.
	LastWritten(context.Context, *LastWrittenRequest) (*LastWrittenResponse, error)
	Ancestors(context.Context, *AncestorsRequest) (*StringList, error)
	Descendants(context.Context, *DescendantsRequest) (*DocIDList, error)
	// Query is the server-side composer for structured queries: anchor
	// narrowing via the inverted index + per-doc clause evaluation. Lets
	// non-Go clients run a multi-clause query in one round-trip instead
	// of replicating the talon-language adapter's composition logic.
	// Supported clauses: Pattern, Predicate, Or, Not, FullText.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// QueryAsOf runs the same structured composer as Query but against a
	// reconstruction of the store as it existed at at_unix_nanos. Each
	// document is rebuilt from its version history (latest version whose
	// write time is <= the timestamp; documents created later, or deleted
	// by then, are absent). Backs the FactStore TimeTraveler capability
	// that powers `was <condition> N <unit> ago` detect conditions.
	QueryAsOf(context.Context, *QueryAsOfRequest) (*QueryResponse, error)
	// SequenceJoin scans temporal indexes for one or more items and
	// returns the items whose event log contains the requested step
	// sequence in order, with total span at most window_nanos. Empty
	// item_ids means scan every item under entity_id.
	SequenceJoin(context.Context, *SequenceJoinRequest) (*SequenceJoinResponse, error)
	// ClusterQuery walks a (entity, itemID)'s temporal index and returns
	// non-overlapping clusters of events whose total span is at most
	// window_nanos and whose size is at least min_size. Replaces the
	// client-side "fetch all events + count" pattern for "N+ records
	// within W" detect blocks.
	ClusterQuery(context.Context, *ClusterQueryRequest) (*ClusterQueryResponse, error)
	// Vector index — per-scope HNSW with dimension locked on first
	// insert. talon-db hosts one logical index per (entity, scope), so a
	// single tenant can hold multiple embedding models with different
	// dimensions side-by-side without cross-contamination.
	VectorInsert(context.Context, *VectorInsertRequest) (*emptypb.Empty, error)
	VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error)
	VectorDelete(context.Context, *VectorDeleteRequest) (*emptypb.Empty, error)
	VectorDropScope(context.Context, *VectorDropScopeRequest) (*emptypb.Empty, error)
	VectorListScopes(context.Context, *VectorListScopesRequest) (*VectorListScopesResponse, error)
	// Subscribe streams MutationEvents for every committed Put / Delete.
	// The server-side stream stays open until the client cancels or the
	// server shuts down. SubscribeRequest filters narrow the stream
	// server-side; an empty entity_id matches every tenant, an empty
	// doc_id_prefix matches every doc.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[MutationEvent]) error
	// Operational
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	mustEmbedUnimplementedTalonDBServiceServer()
}

// UnimplementedTalonDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTalonDBServiceServer struct{}

func (UnimplementedTalonDBServiceServer) Put(context.Context, *PutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedTalonDBServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTalonDBServiceServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTalonDBServiceServer) BatchPut(context.Context, *BatchPutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPut not implemented")
}
func (UnimplementedTalonDBServiceServer) Lookup(context.Context, *LookupRequest) (*DocIDList, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedTalonDBServiceServer) LookupPrefix(context.Context, *LookupPrefixRequest) (*DocIDList, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupPrefix not implemented")
}
func (UnimplementedTalonDBServiceServer) LookupNumericRange(context.Context, *NumericRangeRequest) (*DocIDList, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupNumericRange not implemented")
}
func (UnimplementedTalonDBServiceServer) WindowQuery(context.Context, *WindowRequest) (*WindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WindowQuery not implemented")
}
func (UnimplementedTalonDBServiceServer) GroupCount(context.Context, *GroupRequest) (*GroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupCount not implemented")
}
func (UnimplementedTalonDBServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedTalonDBServiceServer) LastSeen(context.Context, *LastSeenRequest) (*LastSeenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LastSeen not implemented")
}
func (UnimplementedTalonDBServiceServer) LastWritten(context.Context, *LastWrittenRequest) (*LastWrittenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LastWritten not implemented")
}
func (UnimplementedTalonDBServiceServer) Ancestors(context.Context, *AncestorsRequest) (*StringList, error) {
	return nil, status.Error(codes.Unimplemented, "method Ancestors not implemented")
}
func (UnimplementedTalonDBServiceServer) Descendants(context.Context, *DescendantsRequest) (*DocIDList, error) {
	return nil, status.Error(codes.Unimplemented, "method Descendants not implemented")
}
func (UnimplementedTalonDBServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedTalonDBServiceServer) QueryAsOf(context.Context, *QueryAsOfRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAsOf not implemented")
}
func (UnimplementedTalonDBServiceServer) SequenceJoin(context.Context, *SequenceJoinRequest) (*SequenceJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SequenceJoin not implemented")
}
func (UnimplementedTalonDBServiceServer) ClusterQuery(context.Context, *ClusterQueryRequest) (*ClusterQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterQuery not implemented")
}
func (UnimplementedTalonDBServiceServer) VectorInsert(context.Context, *VectorInsertRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorInsert not implemented")
}
func (UnimplementedTalonDBServiceServer) VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorSearch not implemented")
}
func (UnimplementedTalonDBServiceServer) VectorDelete(context.Context, *VectorDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorDelete not implemented")
}
func (UnimplementedTalonDBServiceServer) VectorDropScope(context.Context, *VectorDropScopeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorDropScope not implemented")
}
func (UnimplementedTalonDBServiceServer) VectorListScopes(context.Context, *VectorListScopesRequest) (*VectorListScopesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorListScopes not implemented")
}
func (UnimplementedTalonDBServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[MutationEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTalonDBServiceServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTalonDBServiceServer) mustEmbedUnimplementedTalonDBServiceServer() {}
func (UnimplementedTalonDBServiceServer) testEmbeddedByValue()                        {}

// UnsafeTalonDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TalonDBServiceServer will
// result in compilation errors.
type UnsafeTalonDBServiceServer interface {
	mustEmbedUnimplementedTalonDBServiceServer()
}

func RegisterTalonDBServiceServer(s grpc.ServiceRegistrar, srv TalonDBServiceServer) {
	// If the following call panics, it indicates UnimplementedTalonDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TalonDBService_ServiceDesc, srv)
}

func _TalonDBService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_BatchPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).BatchPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_BatchPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).BatchPut(ctx, req.(*BatchPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_LookupPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).LookupPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_LookupPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).LookupPrefix(ctx, req.(*LookupPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_LookupNumericRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumericRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).LookupNumericRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_LookupNumericRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).LookupNumericRange(ctx, req.(*NumericRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_WindowQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).WindowQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_WindowQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).WindowQuery(ctx, req.(*WindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_GroupCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).GroupCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_GroupCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).GroupCount(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_LastSeen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastSeenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).LastSeen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_LastSeen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).LastSeen(ctx, req.(*LastSeenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_LastWritten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastWrittenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).LastWritten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_LastWritten_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).LastWritten(ctx, req.(*LastWrittenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_Ancestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AncestorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).Ancestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_Ancestors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).Ancestors(ctx, req.(*AncestorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_Descendants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescendantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).Descendants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_Descendants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).Descendants(ctx, req.(*DescendantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_QueryAsOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAsOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).QueryAsOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_QueryAsOf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).QueryAsOf(ctx, req.(*QueryAsOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_SequenceJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SequenceJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).SequenceJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_SequenceJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).SequenceJoin(ctx, req.(*SequenceJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_ClusterQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).ClusterQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_ClusterQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).ClusterQuery(ctx, req.(*ClusterQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_VectorInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).VectorInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_VectorInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).VectorInsert(ctx, req.(*VectorInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_VectorSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).VectorSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_VectorSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).VectorSearch(ctx, req.(*VectorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_VectorDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).VectorDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_VectorDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).VectorDelete(ctx, req.(*VectorDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_VectorDropScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorDropScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).VectorDropScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_VectorDropScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).VectorDropScope(ctx, req.(*VectorDropScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_VectorListScopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorListScopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).VectorListScopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_VectorListScopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).VectorListScopes(ctx, req.(*VectorListScopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalonDBService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TalonDBServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, MutationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TalonDBService_SubscribeServer = grpc.ServerStreamingServer[MutationEvent]

func _TalonDBService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalonDBServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalonDBService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalonDBServiceServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TalonDBService_ServiceDesc is the grpc.ServiceDesc for TalonDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TalonDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opentalon.talondb.v1.TalonDBService",
	HandlerType: (*TalonDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _TalonDBService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TalonDBService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TalonDBService_Delete_Handler,
		},
		{
			MethodName: "BatchPut",
			Handler:    _TalonDBService_BatchPut_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _TalonDBService_Lookup_Handler,
		},
		{
			MethodName: "LookupPrefix",
			Handler:    _TalonDBService_LookupPrefix_Handler,
		},
		{
			MethodName: "LookupNumericRange",
			Handler:    _TalonDBService_LookupNumericRange_Handler,
		},
		{
			MethodName: "WindowQuery",
			Handler:    _TalonDBService_WindowQuery_Handler,
		},
		{
			MethodName: "GroupCount",
			Handler:    _TalonDBService_GroupCount_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _TalonDBService_Stats_Handler,
		},
		{
			MethodName: "LastSeen",
			Handler:    _TalonDBService_LastSeen_Handler,
		},
		{
			MethodName: "LastWritten",
			Handler:    _TalonDBService_LastWritten_Handler,
		},
		{
			MethodName: "Ancestors",
			Handler:    _TalonDBService_Ancestors_Handler,
		},
		{
			MethodName: "Descendants",
			Handler:    _TalonDBService_Descendants_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _TalonDBService_Query_Handler,
		},
		{
			MethodName: "QueryAsOf",
			Handler:    _TalonDBService_QueryAsOf_Handler,
		},
		{
			MethodName: "SequenceJoin",
			Handler:    _TalonDBService_SequenceJoin_Handler,
		},
		{
			MethodName: "ClusterQuery",
			Handler:    _TalonDBService_ClusterQuery_Handler,
		},
		{
			MethodName: "VectorInsert",
			Handler:    _TalonDBService_VectorInsert_Handler,
		},
		{
			MethodName: "VectorSearch",
			Handler:    _TalonDBService_VectorSearch_Handler,
		},
		{
			MethodName: "VectorDelete",
			Handler:    _TalonDBService_VectorDelete_Handler,
		},
		{
			MethodName: "VectorDropScope",
			Handler:    _TalonDBService_VectorDropScope_Handler,
		},
		{
			MethodName: "VectorListScopes",
			Handler:    _TalonDBService_VectorListScopes_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _TalonDBService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _TalonDBService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/talondb.proto",
}
