// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/tlndb.proto

package tlndbpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TlnDBService_Put_FullMethodName                = "/opentalon.tlndb.v1.TlnDBService/Put"
	TlnDBService_Get_FullMethodName                = "/opentalon.tlndb.v1.TlnDBService/Get"
	TlnDBService_Delete_FullMethodName             = "/opentalon.tlndb.v1.TlnDBService/Delete"
	TlnDBService_BatchPut_FullMethodName           = "/opentalon.tlndb.v1.TlnDBService/BatchPut"
	TlnDBService_Lookup_FullMethodName             = "/opentalon.tlndb.v1.TlnDBService/Lookup"
	TlnDBService_LookupPrefix_FullMethodName       = "/opentalon.tlndb.v1.TlnDBService/LookupPrefix"
	TlnDBService_LookupNumericRange_FullMethodName = "/opentalon.tlndb.v1.TlnDBService/LookupNumericRange"
	TlnDBService_WindowQuery_FullMethodName        = "/opentalon.tlndb.v1.TlnDBService/WindowQuery"
	TlnDBService_GroupCount_FullMethodName         = "/opentalon.tlndb.v1.TlnDBService/GroupCount"
	TlnDBService_Stats_FullMethodName              = "/opentalon.tlndb.v1.TlnDBService/Stats"
	TlnDBService_LastSeen_FullMethodName           = "/opentalon.tlndb.v1.TlnDBService/LastSeen"
	TlnDBService_LastWritten_FullMethodName        = "/opentalon.tlndb.v1.TlnDBService/LastWritten"
	TlnDBService_Ancestors_FullMethodName          = "/opentalon.tlndb.v1.TlnDBService/Ancestors"
	TlnDBService_Descendants_FullMethodName        = "/opentalon.tlndb.v1.TlnDBService/Descendants"
	TlnDBService_Query_FullMethodName              = "/opentalon.tlndb.v1.TlnDBService/Query"
	TlnDBService_QueryAsOf_FullMethodName          = "/opentalon.tlndb.v1.TlnDBService/QueryAsOf"
	TlnDBService_SequenceJoin_FullMethodName       = "/opentalon.tlndb.v1.TlnDBService/SequenceJoin"
	TlnDBService_ClusterQuery_FullMethodName       = "/opentalon.tlndb.v1.TlnDBService/ClusterQuery"
	TlnDBService_VectorInsert_FullMethodName       = "/opentalon.tlndb.v1.TlnDBService/VectorInsert"
	TlnDBService_VectorSearch_FullMethodName       = "/opentalon.tlndb.v1.TlnDBService/VectorSearch"
	TlnDBService_VectorDelete_FullMethodName       = "/opentalon.tlndb.v1.TlnDBService/VectorDelete"
	TlnDBService_VectorDropScope_FullMethodName    = "/opentalon.tlndb.v1.TlnDBService/VectorDropScope"
	TlnDBService_VectorListScopes_FullMethodName   = "/opentalon.tlndb.v1.TlnDBService/VectorListScopes"
	TlnDBService_Subscribe_FullMethodName          = "/opentalon.tlndb.v1.TlnDBService/Subscribe"
	TlnDBService_Replicate_FullMethodName          = "/opentalon.tlndb.v1.TlnDBService/Replicate"
	TlnDBService_Snapshot_FullMethodName           = "/opentalon.tlndb.v1.TlnDBService/Snapshot"
	TlnDBService_Health_FullMethodName             = "/opentalon.tlndb.v1.TlnDBService/Health"
)

// TlnDBServiceClient is the client API for TlnDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TlnDBService is the wire surface exposed by `tlndb-server`. The
// gRPC service maps 1:1 to the tlndb.IndexedStore Go interface.
//
// Two transports speak this schema:
//   - gRPC, the primary protocol (Unix socket default, TCP optional).
//   - HTTP/JSON, generated by grpc-gateway from this file, useful for
//     curl-based debugging and non-Go clients. The HTTP paths follow
//     the Postgres-flavoured convention of operation-as-path, request
//     body as JSON.
type TlnDBServiceClient interface {
	// DocumentStore surface (entityID, docID) → bytes
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BatchPut(ctx context.Context, in *BatchPutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// IndexedStore lookup surface
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*DocIDList, error)
	LookupPrefix(ctx context.Context, in *LookupPrefixRequest, opts ...grpc.CallOption) (*DocIDList, error)
	LookupNumericRange(ctx context.Context, in *NumericRangeRequest, opts ...grpc.CallOption) (*DocIDList, error)
	WindowQuery(ctx context.Context, in *WindowRequest, opts ...grpc.CallOption) (*WindowResponse, error)
	GroupCount(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	LastSeen(ctx context.Context, in *LastSeenRequest, opts ...grpc.CallOption) (*LastSeenResponse, error)
	// LastWritten returns a document's updated_at time (doc-level
	// granularity). Backs the FactStore Freshness capability used for fact
	// staleness / the enrich block.
	LastWritten(ctx context.Context, in *LastWrittenRequest, opts ...grpc.CallOption) (*LastWrittenResponse, error)
	Ancestors(ctx context.Context, in *AncestorsRequest, opts ...grpc.CallOption) (*StringList, error)
	Descendants(ctx context.Context, in *DescendantsRequest, opts ...grpc.CallOption) (*DocIDList, error)
	// Query is the server-side composer for structured queries: anchor
	// narrowing via the inverted index + per-doc clause evaluation. Lets
	// non-Go clients run a multi-clause query in one round-trip instead
	// of replicating the tln-language adapter's composition logic.
	// Supported clauses: Pattern, Predicate, Or, Not, FullText.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// QueryAsOf runs the same structured composer as Query but against a
	// reconstruction of the store as it existed at at_unix_nanos. Each
	// document is rebuilt from its version history (latest version whose
	// write time is <= the timestamp; documents created later, or deleted
	// by then, are absent). Backs the FactStore TimeTraveler capability
	// that powers `was <condition> N <unit> ago` detect conditions.
	QueryAsOf(ctx context.Context, in *QueryAsOfRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// SequenceJoin scans temporal indexes for one or more items and
	// returns the items whose event log contains the requested step
	// sequence in order, with total span at most window_nanos. Empty
	// item_ids means scan every item under entity_id.
	SequenceJoin(ctx context.Context, in *SequenceJoinRequest, opts ...grpc.CallOption) (*SequenceJoinResponse, error)
	// ClusterQuery walks a (entity, itemID)'s temporal index and returns
	// non-overlapping clusters of events whose total span is at most
	// window_nanos and whose size is at least min_size. Replaces the
	// client-side "fetch all events + count" pattern for "N+ records
	// within W" detect blocks.
	ClusterQuery(ctx context.Context, in *ClusterQueryRequest, opts ...grpc.CallOption) (*ClusterQueryResponse, error)
	// Vector index — per-scope HNSW with dimension locked on first
	// insert. tln-db hosts one logical index per (entity, scope), so a
	// single tenant can hold multiple embedding models with different
	// dimensions side-by-side without cross-contamination.
	VectorInsert(ctx context.Context, in *VectorInsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error)
	VectorDelete(ctx context.Context, in *VectorDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	VectorDropScope(ctx context.Context, in *VectorDropScopeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	VectorListScopes(ctx context.Context, in *VectorListScopesRequest, opts ...grpc.CallOption) (*VectorListScopesResponse, error)
	// Subscribe streams MutationEvents for every committed Put / Delete.
	// The server-side stream stays open until the client cancels or the
	// server shuts down. SubscribeRequest filters narrow the stream
	// server-side; an empty entity_id matches every tenant, an empty
	// doc_id_prefix matches every doc.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MutationEvent], error)
	// Replication — async read-replica log shipping. A follower first
	// bootstraps via Snapshot (a consistent bbolt copy + its op-log seq)
	// then tails Replicate from that seq. Both are served only when the
	// leader was started with the replication log enabled.
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OpLogEntry], error)
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error)
	// Operational
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type tlnDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTlnDBServiceClient(cc grpc.ClientConnInterface) TlnDBServiceClient {
	return &tlnDBServiceClient{cc}
}

func (c *tlnDBServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TlnDBService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, TlnDBService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TlnDBService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) BatchPut(ctx context.Context, in *BatchPutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TlnDBService_BatchPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*DocIDList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocIDList)
	err := c.cc.Invoke(ctx, TlnDBService_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) LookupPrefix(ctx context.Context, in *LookupPrefixRequest, opts ...grpc.CallOption) (*DocIDList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocIDList)
	err := c.cc.Invoke(ctx, TlnDBService_LookupPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) LookupNumericRange(ctx context.Context, in *NumericRangeRequest, opts ...grpc.CallOption) (*DocIDList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocIDList)
	err := c.cc.Invoke(ctx, TlnDBService_LookupNumericRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) WindowQuery(ctx context.Context, in *WindowRequest, opts ...grpc.CallOption) (*WindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WindowResponse)
	err := c.cc.Invoke(ctx, TlnDBService_WindowQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) GroupCount(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, TlnDBService_GroupCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, TlnDBService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) LastSeen(ctx context.Context, in *LastSeenRequest, opts ...grpc.CallOption) (*LastSeenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastSeenResponse)
	err := c.cc.Invoke(ctx, TlnDBService_LastSeen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) LastWritten(ctx context.Context, in *LastWrittenRequest, opts ...grpc.CallOption) (*LastWrittenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastWrittenResponse)
	err := c.cc.Invoke(ctx, TlnDBService_LastWritten_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) Ancestors(ctx context.Context, in *AncestorsRequest, opts ...grpc.CallOption) (*StringList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringList)
	err := c.cc.Invoke(ctx, TlnDBService_Ancestors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) Descendants(ctx context.Context, in *DescendantsRequest, opts ...grpc.CallOption) (*DocIDList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocIDList)
	err := c.cc.Invoke(ctx, TlnDBService_Descendants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, TlnDBService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) QueryAsOf(ctx context.Context, in *QueryAsOfRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, TlnDBService_QueryAsOf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) SequenceJoin(ctx context.Context, in *SequenceJoinRequest, opts ...grpc.CallOption) (*SequenceJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SequenceJoinResponse)
	err := c.cc.Invoke(ctx, TlnDBService_SequenceJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) ClusterQuery(ctx context.Context, in *ClusterQueryRequest, opts ...grpc.CallOption) (*ClusterQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterQueryResponse)
	err := c.cc.Invoke(ctx, TlnDBService_ClusterQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) VectorInsert(ctx context.Context, in *VectorInsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TlnDBService_VectorInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorSearchResponse)
	err := c.cc.Invoke(ctx, TlnDBService_VectorSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) VectorDelete(ctx context.Context, in *VectorDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TlnDBService_VectorDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) VectorDropScope(ctx context.Context, in *VectorDropScopeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TlnDBService_VectorDropScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) VectorListScopes(ctx context.Context, in *VectorListScopesRequest, opts ...grpc.CallOption) (*VectorListScopesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorListScopesResponse)
	err := c.cc.Invoke(ctx, TlnDBService_VectorListScopes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tlnDBServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MutationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TlnDBService_ServiceDesc.Streams[0], TlnDBService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, MutationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TlnDBService_SubscribeClient = grpc.ServerStreamingClient[MutationEvent]

func (c *tlnDBServiceClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OpLogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TlnDBService_ServiceDesc.Streams[1], TlnDBService_Replicate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplicateRequest, OpLogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TlnDBService_ReplicateClient = grpc.ServerStreamingClient[OpLogEntry]

func (c *tlnDBServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TlnDBService_ServiceDesc.Streams[2], TlnDBService_Snapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotRequest, SnapshotChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TlnDBService_SnapshotClient = grpc.ServerStreamingClient[SnapshotChunk]

func (c *tlnDBServiceClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TlnDBService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TlnDBServiceServer is the server API for TlnDBService service.
// All implementations must embed UnimplementedTlnDBServiceServer
// for forward compatibility.
//
// TlnDBService is the wire surface exposed by `tlndb-server`. The
// gRPC service maps 1:1 to the tlndb.IndexedStore Go interface.
//
// Two transports speak this schema:
//   - gRPC, the primary protocol (Unix socket default, TCP optional).
//   - HTTP/JSON, generated by grpc-gateway from this file, useful for
//     curl-based debugging and non-Go clients. The HTTP paths follow
//     the Postgres-flavoured convention of operation-as-path, request
//     body as JSON.
type TlnDBServiceServer interface {
	// DocumentStore surface (entityID, docID) → bytes
	Put(context.Context, *PutRequest) (*emptypb.Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	BatchPut(context.Context, *BatchPutRequest) (*emptypb.Empty, error)
	// IndexedStore lookup surface
	Lookup(context.Context, *LookupRequest) (*DocIDList, error)
	LookupPrefix(context.Context, *LookupPrefixRequest) (*DocIDList, error)
	LookupNumericRange(context.Context, *NumericRangeRequest) (*DocIDList, error)
	WindowQuery(context.Context, *WindowRequest) (*WindowResponse, error)
	GroupCount(context.Context, *GroupRequest) (*GroupResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	LastSeen(context.Context, *LastSeenRequest) (*LastSeenResponse, error)
	// LastWritten returns a document's updated_at time (doc-level
	// granularity). Backs the FactStore Freshness capability used for fact
	// staleness / the enrich block.
	LastWritten(context.Context, *LastWrittenRequest) (*LastWrittenResponse, error)
	Ancestors(context.Context, *AncestorsRequest) (*StringList, error)
	Descendants(context.Context, *DescendantsRequest) (*DocIDList, error)
	// Query is the server-side composer for structured queries: anchor
	// narrowing via the inverted index + per-doc clause evaluation. Lets
	// non-Go clients run a multi-clause query in one round-trip instead
	// of replicating the tln-language adapter's composition logic.
	// Supported clauses: Pattern, Predicate, Or, Not, FullText.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// QueryAsOf runs the same structured composer as Query but against a
	// reconstruction of the store as it existed at at_unix_nanos. Each
	// document is rebuilt from its version history (latest version whose
	// write time is <= the timestamp; documents created later, or deleted
	// by then, are absent). Backs the FactStore TimeTraveler capability
	// that powers `was <condition> N <unit> ago` detect conditions.
	QueryAsOf(context.Context, *QueryAsOfRequest) (*QueryResponse, error)
	// SequenceJoin scans temporal indexes for one or more items and
	// returns the items whose event log contains the requested step
	// sequence in order, with total span at most window_nanos. Empty
	// item_ids means scan every item under entity_id.
	SequenceJoin(context.Context, *SequenceJoinRequest) (*SequenceJoinResponse, error)
	// ClusterQuery walks a (entity, itemID)'s temporal index and returns
	// non-overlapping clusters of events whose total span is at most
	// window_nanos and whose size is at least min_size. Replaces the
	// client-side "fetch all events + count" pattern for "N+ records
	// within W" detect blocks.
	ClusterQuery(context.Context, *ClusterQueryRequest) (*ClusterQueryResponse, error)
	// Vector index — per-scope HNSW with dimension locked on first
	// insert. tln-db hosts one logical index per (entity, scope), so a
	// single tenant can hold multiple embedding models with different
	// dimensions side-by-side without cross-contamination.
	VectorInsert(context.Context, *VectorInsertRequest) (*emptypb.Empty, error)
	VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error)
	VectorDelete(context.Context, *VectorDeleteRequest) (*emptypb.Empty, error)
	VectorDropScope(context.Context, *VectorDropScopeRequest) (*emptypb.Empty, error)
	VectorListScopes(context.Context, *VectorListScopesRequest) (*VectorListScopesResponse, error)
	// Subscribe streams MutationEvents for every committed Put / Delete.
	// The server-side stream stays open until the client cancels or the
	// server shuts down. SubscribeRequest filters narrow the stream
	// server-side; an empty entity_id matches every tenant, an empty
	// doc_id_prefix matches every doc.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[MutationEvent]) error
	// Replication — async read-replica log shipping. A follower first
	// bootstraps via Snapshot (a consistent bbolt copy + its op-log seq)
	// then tails Replicate from that seq. Both are served only when the
	// leader was started with the replication log enabled.
	Replicate(*ReplicateRequest, grpc.ServerStreamingServer[OpLogEntry]) error
	Snapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error
	// Operational
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	mustEmbedUnimplementedTlnDBServiceServer()
}

// UnimplementedTlnDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTlnDBServiceServer struct{}

func (UnimplementedTlnDBServiceServer) Put(context.Context, *PutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedTlnDBServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTlnDBServiceServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTlnDBServiceServer) BatchPut(context.Context, *BatchPutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPut not implemented")
}
func (UnimplementedTlnDBServiceServer) Lookup(context.Context, *LookupRequest) (*DocIDList, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedTlnDBServiceServer) LookupPrefix(context.Context, *LookupPrefixRequest) (*DocIDList, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupPrefix not implemented")
}
func (UnimplementedTlnDBServiceServer) LookupNumericRange(context.Context, *NumericRangeRequest) (*DocIDList, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupNumericRange not implemented")
}
func (UnimplementedTlnDBServiceServer) WindowQuery(context.Context, *WindowRequest) (*WindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WindowQuery not implemented")
}
func (UnimplementedTlnDBServiceServer) GroupCount(context.Context, *GroupRequest) (*GroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupCount not implemented")
}
func (UnimplementedTlnDBServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedTlnDBServiceServer) LastSeen(context.Context, *LastSeenRequest) (*LastSeenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LastSeen not implemented")
}
func (UnimplementedTlnDBServiceServer) LastWritten(context.Context, *LastWrittenRequest) (*LastWrittenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LastWritten not implemented")
}
func (UnimplementedTlnDBServiceServer) Ancestors(context.Context, *AncestorsRequest) (*StringList, error) {
	return nil, status.Error(codes.Unimplemented, "method Ancestors not implemented")
}
func (UnimplementedTlnDBServiceServer) Descendants(context.Context, *DescendantsRequest) (*DocIDList, error) {
	return nil, status.Error(codes.Unimplemented, "method Descendants not implemented")
}
func (UnimplementedTlnDBServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedTlnDBServiceServer) QueryAsOf(context.Context, *QueryAsOfRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAsOf not implemented")
}
func (UnimplementedTlnDBServiceServer) SequenceJoin(context.Context, *SequenceJoinRequest) (*SequenceJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SequenceJoin not implemented")
}
func (UnimplementedTlnDBServiceServer) ClusterQuery(context.Context, *ClusterQueryRequest) (*ClusterQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterQuery not implemented")
}
func (UnimplementedTlnDBServiceServer) VectorInsert(context.Context, *VectorInsertRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorInsert not implemented")
}
func (UnimplementedTlnDBServiceServer) VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorSearch not implemented")
}
func (UnimplementedTlnDBServiceServer) VectorDelete(context.Context, *VectorDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorDelete not implemented")
}
func (UnimplementedTlnDBServiceServer) VectorDropScope(context.Context, *VectorDropScopeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorDropScope not implemented")
}
func (UnimplementedTlnDBServiceServer) VectorListScopes(context.Context, *VectorListScopesRequest) (*VectorListScopesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorListScopes not implemented")
}
func (UnimplementedTlnDBServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[MutationEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTlnDBServiceServer) Replicate(*ReplicateRequest, grpc.ServerStreamingServer[OpLogEntry]) error {
	return status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedTlnDBServiceServer) Snapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error {
	return status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedTlnDBServiceServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTlnDBServiceServer) mustEmbedUnimplementedTlnDBServiceServer() {}
func (UnimplementedTlnDBServiceServer) testEmbeddedByValue()                      {}

// UnsafeTlnDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TlnDBServiceServer will
// result in compilation errors.
type UnsafeTlnDBServiceServer interface {
	mustEmbedUnimplementedTlnDBServiceServer()
}

func RegisterTlnDBServiceServer(s grpc.ServiceRegistrar, srv TlnDBServiceServer) {
	// If the following call panics, it indicates UnimplementedTlnDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TlnDBService_ServiceDesc, srv)
}

func _TlnDBService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_BatchPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).BatchPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_BatchPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).BatchPut(ctx, req.(*BatchPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_LookupPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).LookupPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_LookupPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).LookupPrefix(ctx, req.(*LookupPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_LookupNumericRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumericRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).LookupNumericRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_LookupNumericRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).LookupNumericRange(ctx, req.(*NumericRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_WindowQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).WindowQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_WindowQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).WindowQuery(ctx, req.(*WindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_GroupCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).GroupCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_GroupCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).GroupCount(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_LastSeen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastSeenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).LastSeen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_LastSeen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).LastSeen(ctx, req.(*LastSeenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_LastWritten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastWrittenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).LastWritten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_LastWritten_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).LastWritten(ctx, req.(*LastWrittenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_Ancestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AncestorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).Ancestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_Ancestors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).Ancestors(ctx, req.(*AncestorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_Descendants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescendantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).Descendants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_Descendants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).Descendants(ctx, req.(*DescendantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_QueryAsOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAsOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).QueryAsOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_QueryAsOf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).QueryAsOf(ctx, req.(*QueryAsOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_SequenceJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SequenceJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).SequenceJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_SequenceJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).SequenceJoin(ctx, req.(*SequenceJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_ClusterQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).ClusterQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_ClusterQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).ClusterQuery(ctx, req.(*ClusterQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_VectorInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).VectorInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_VectorInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).VectorInsert(ctx, req.(*VectorInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_VectorSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).VectorSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_VectorSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).VectorSearch(ctx, req.(*VectorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_VectorDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).VectorDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_VectorDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).VectorDelete(ctx, req.(*VectorDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_VectorDropScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorDropScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).VectorDropScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_VectorDropScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).VectorDropScope(ctx, req.(*VectorDropScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_VectorListScopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorListScopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).VectorListScopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_VectorListScopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).VectorListScopes(ctx, req.(*VectorListScopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TlnDBService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TlnDBServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, MutationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TlnDBService_SubscribeServer = grpc.ServerStreamingServer[MutationEvent]

func _TlnDBService_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReplicateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TlnDBServiceServer).Replicate(m, &grpc.GenericServerStream[ReplicateRequest, OpLogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TlnDBService_ReplicateServer = grpc.ServerStreamingServer[OpLogEntry]

func _TlnDBService_Snapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TlnDBServiceServer).Snapshot(m, &grpc.GenericServerStream[SnapshotRequest, SnapshotChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TlnDBService_SnapshotServer = grpc.ServerStreamingServer[SnapshotChunk]

func _TlnDBService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlnDBServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlnDBService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlnDBServiceServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TlnDBService_ServiceDesc is the grpc.ServiceDesc for TlnDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TlnDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opentalon.tlndb.v1.TlnDBService",
	HandlerType: (*TlnDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _TlnDBService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TlnDBService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TlnDBService_Delete_Handler,
		},
		{
			MethodName: "BatchPut",
			Handler:    _TlnDBService_BatchPut_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _TlnDBService_Lookup_Handler,
		},
		{
			MethodName: "LookupPrefix",
			Handler:    _TlnDBService_LookupPrefix_Handler,
		},
		{
			MethodName: "LookupNumericRange",
			Handler:    _TlnDBService_LookupNumericRange_Handler,
		},
		{
			MethodName: "WindowQuery",
			Handler:    _TlnDBService_WindowQuery_Handler,
		},
		{
			MethodName: "GroupCount",
			Handler:    _TlnDBService_GroupCount_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _TlnDBService_Stats_Handler,
		},
		{
			MethodName: "LastSeen",
			Handler:    _TlnDBService_LastSeen_Handler,
		},
		{
			MethodName: "LastWritten",
			Handler:    _TlnDBService_LastWritten_Handler,
		},
		{
			MethodName: "Ancestors",
			Handler:    _TlnDBService_Ancestors_Handler,
		},
		{
			MethodName: "Descendants",
			Handler:    _TlnDBService_Descendants_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _TlnDBService_Query_Handler,
		},
		{
			MethodName: "QueryAsOf",
			Handler:    _TlnDBService_QueryAsOf_Handler,
		},
		{
			MethodName: "SequenceJoin",
			Handler:    _TlnDBService_SequenceJoin_Handler,
		},
		{
			MethodName: "ClusterQuery",
			Handler:    _TlnDBService_ClusterQuery_Handler,
		},
		{
			MethodName: "VectorInsert",
			Handler:    _TlnDBService_VectorInsert_Handler,
		},
		{
			MethodName: "VectorSearch",
			Handler:    _TlnDBService_VectorSearch_Handler,
		},
		{
			MethodName: "VectorDelete",
			Handler:    _TlnDBService_VectorDelete_Handler,
		},
		{
			MethodName: "VectorDropScope",
			Handler:    _TlnDBService_VectorDropScope_Handler,
		},
		{
			MethodName: "VectorListScopes",
			Handler:    _TlnDBService_VectorListScopes_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _TlnDBService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _TlnDBService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Replicate",
			Handler:       _TlnDBService_Replicate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Snapshot",
			Handler:       _TlnDBService_Snapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/tlndb.proto",
}
